#ifndef ICB_SHADERS_H
#define ICB_SHADERS_H

static const char* draw_icb_conversion_shader =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"struct DrawCommand {\n"
"    uint draw_id;\n"
"    uint vertex_count;\n"
"    uint instance_count;\n"
"    uint first_vertex;\n"
"    uint first_instance;\n"
"};\n"
"\n"
"struct PerDrawConstant {\n"
"    uint data[32];\n"
"    uint draw_id;\n"
"    uint _pad[31];\n"
"};\n"
"\n"
"struct Arguments {\n"
"    command_buffer cmd_buffer;\n"
"};\n"
"\n"
"kernel void encode_draws(\n"
"    device const DrawCommand* draw_commands       [[buffer(0)]],\n"
"    device const uint*        draw_count          [[buffer(1)]],\n"
"    device const uint*        primitive_type_buf  [[buffer(2)]],\n"
"    device Arguments*         args                [[buffer(3)]],\n"
"    device PerDrawConstant*   per_draw_constants  [[buffer(4)]],\n"
"    device const uint*        resource_heap       [[buffer(5)]],\n"
"    device const uint*        sampler_heap        [[buffer(6)]],\n"
"    device atomic_uint*       draw_id_counter     [[buffer(7)]],\n"
"    uint gid [[thread_position_in_grid]])\n"
"{\n"
"    if (gid >= *draw_count)\n"
"        return;\n"
"\n"
"    const DrawCommand draw = draw_commands[gid];\n"
"    device PerDrawConstant* dst = per_draw_constants + gid;\n"
"\n"
"    // Copy base constants from slot 0\n"
"    if (gid > 0) {\n"
"        device uint8_t* dPtr = reinterpret_cast<device uint8_t*>(dst);\n"
"        device const uint8_t* sPtr = reinterpret_cast<device const uint8_t*>(per_draw_constants);\n"
"        for (uint i = 0; i < 128; ++i)\n"
"            dPtr[i] = sPtr[i];\n"
"    }\n"
"\n"
"    dst->draw_id = atomic_fetch_add_explicit(draw_id_counter, 1, memory_order_relaxed);\n"
"\n"
"    uint primitive = primitive_type_buf[0];\n"
"    primitive_type pt;\n"
"    switch (primitive) {\n"
"        case 0: pt = primitive_type::point;    break;\n"
"        case 1: pt = primitive_type::line;     break;\n"
"        case 2: pt = primitive_type::triangle; break;\n"
"        default: return;\n"
"    }\n"
"\n"
"    render_command rc(args->cmd_buffer, gid);\n"
"    rc.set_vertex_buffer(resource_heap, 0);\n"
"    rc.set_fragment_buffer(resource_heap, 0);\n"
"    rc.set_vertex_buffer(sampler_heap, 1);\n"
"    rc.set_fragment_buffer(sampler_heap, 1);\n"
"    rc.set_vertex_buffer(dst, 2);\n"
"    rc.set_fragment_buffer(dst, 2);\n"
"    rc.draw_primitives(pt, draw.first_vertex, draw.vertex_count, draw.instance_count, draw.first_instance);\n"
"}\n";

static const char* draw_indexed_icb_conversion_shader =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"struct DrawIndexedCommand {\n"
"    uint draw_id;\n"
"    uint index_count;\n"
"    uint instance_count;\n"
"    uint first_index;\n"
"    uint vertex_offset;\n"
"    uint first_instance;\n"
"};\n"
"\n"
"struct PerDrawConstant {\n"
"    uint data[32];\n"
"    uint draw_id;\n"
"    uint _pad[31];\n"
"};\n"
"\n"
"struct Arguments {\n"
"    command_buffer cmd_buffer;\n"
"    device const uint* index_buffer;\n"
"};\n"
"\n"
"kernel void encode_draws(\n"
"    device const DrawIndexedCommand* draw_commands       [[buffer(0)]],\n"
"    device const uint*        draw_count          [[buffer(1)]],\n"
"    device const uint*        primitive_type_buf  [[buffer(2)]],\n"
"    device Arguments*         args                [[buffer(3)]],\n"
"    device PerDrawConstant*   per_draw_constants  [[buffer(4)]],\n"
"    device const uint*        resource_heap       [[buffer(5)]],\n"
"    device const uint*        sampler_heap        [[buffer(6)]],\n"
"    device atomic_uint*       draw_id_counter [[buffer(7)]],\n"
"    uint gid [[thread_position_in_grid]])\n"
"{\n"
"    if (gid >= *draw_count)\n"
"        return;\n"
"\n"
"    const DrawIndexedCommand draw = draw_commands[gid];\n"
"    device PerDrawConstant* dst = per_draw_constants + gid;\n"
"\n"
"    // Copy base constants from slot 0\n"
"    if (gid > 0) {\n"
"        device uint8_t* dPtr = reinterpret_cast<device uint8_t*>(dst);\n"
"        device const uint8_t* sPtr = reinterpret_cast<device const uint8_t*>(per_draw_constants);\n"
"        for (uint i = 0; i < 128; ++i)\n"
"            dPtr[i] = sPtr[i];\n"
"    }\n"
"\n"
"    dst->draw_id = atomic_fetch_add_explicit(draw_id_counter, 1, memory_order_relaxed);\n"
"\n"
"    uint primitive = primitive_type_buf[0];\n"
"    primitive_type pt;\n"
"    switch (primitive) {\n"
"        case 0: pt = primitive_type::point;    break;\n"
"        case 1: pt = primitive_type::line;     break;\n"
"        case 2: pt = primitive_type::triangle; break;\n"
"        default: return;\n"
"    }\n"
"\n"
"    render_command rc(args->cmd_buffer, gid);\n"
"    rc.set_vertex_buffer(resource_heap, 0);\n"
"    rc.set_fragment_buffer(resource_heap, 0);\n"
"    rc.set_vertex_buffer(sampler_heap, 1);\n"
"    rc.set_fragment_buffer(sampler_heap, 1);\n"
"    rc.set_vertex_buffer(dst, 2);\n"
"    rc.set_fragment_buffer(dst, 2);\n"
"    rc.draw_indexed_primitives(pt, draw.index_count, args->index_buffer, draw.instance_count, draw.first_index, draw.first_instance);\n"
"}\n";

static const char* dispatch_icb_conversion_shader =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"struct DispatchCommand {\n"
"    uint group_count_x;\n"
"    uint group_count_y;\n"
"    uint group_count_z;\n"
"};\n"
"\n"
"struct Arguments {\n"
"    command_buffer cmd_buffer;\n"
"    \n"
"    uint threads_per_group_x;\n"
"    uint threads_per_group_y;\n"
"    uint threads_per_group_z;\n"
"};\n"
"\n"
"kernel void encode_draws(\n"
"    device const DispatchCommand* dispatch_command [[buffer(0)]],\n"
"    device Arguments* args [[buffer(1)]])\n"
"{\n"
"    const DispatchCommand dispatch = dispatch_command[0];\n"
"\n"
"    compute_command cc(args->cmd_buffer, 0);\n"
"    cc.concurrent_dispatch_threadgroups(\n"
"        uint3(dispatch.group_count_x, dispatch.group_count_y, dispatch.group_count_z),\n"
"        uint3(args->threads_per_group_x, args->threads_per_group_y, args->threads_per_group_z)\n"
"    );\n"
"}\n";

static const char* draw_mesh_icb_conversion_shader =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"struct DrawMeshCommand {\n"
"    uint draw_id;\n"
"    uint gx;\n"
"    uint gy;\n"
"    uint gz;\n"
"};\n"
"\n"
"struct PerDrawConstant {\n"
"    uint data[32];\n"
"    uint draw_id;\n"
"    uint _pad[31];\n"
"};\n"
"\n"
"struct Arguments {\n"
"    command_buffer cmd_buffer;\n"
"    \n"
"    uint3 threads_per_object;\n"
"    uint3 threads_per_mesh;\n"
"};\n"
"\n"
"kernel void encode_draws(\n"
"    device const DrawMeshCommand* draw_commands   [[buffer(0)]],\n"
"    device const uint*        draw_count          [[buffer(1)]],\n"
"    device Arguments*         args                [[buffer(2)]],\n"
"    device PerDrawConstant*   per_draw_constants  [[buffer(3)]],\n"
"    device const uint*        resource_heap       [[buffer(4)]],\n"
"    device const uint*        sampler_heap        [[buffer(5)]],\n"
"    device atomic_uint*       draw_id_counter [[buffer(6)]],\n"
"    uint gid [[thread_position_in_grid]])\n"
"{\n"
"    if (gid >= *draw_count)\n"
"        return;\n"
"\n"
"    const DrawMeshCommand draw = draw_commands[gid];\n"
"    device PerDrawConstant* dst = per_draw_constants + gid;\n"
"\n"
"    // Copy base constants from slot 0\n"
"    if (gid > 0) {\n"
"        device uint8_t* dPtr = reinterpret_cast<device uint8_t*>(dst);\n"
"        device const uint8_t* sPtr = reinterpret_cast<device const uint8_t*>(per_draw_constants);\n"
"        for (uint i = 0; i < 128; ++i)\n"
"            dPtr[i] = sPtr[i];\n"
"    }\n"
"    dst->draw_id = atomic_fetch_add_explicit(draw_id_counter, 1, memory_order_relaxed);\n"
"\n"
"    render_command rc(args->cmd_buffer, gid);\n"
"    rc.set_object_buffer(resource_heap, 0);\n"
"    rc.set_mesh_buffer(resource_heap, 0);\n"
"    rc.set_fragment_buffer(resource_heap, 0);\n"
"    rc.set_object_buffer(sampler_heap, 1);\n"
"    rc.set_mesh_buffer(sampler_heap, 1);\n"
"    rc.set_fragment_buffer(sampler_heap, 1);\n"
"    rc.set_object_buffer(dst, 2);\n"
"    rc.set_mesh_buffer(dst, 2);\n"
"    rc.set_fragment_buffer(dst, 2);\n"
"    rc.draw_mesh_threadgroups(\n"
"        uint3(draw.gx, draw.gy, draw.gz),\n"
"        args->threads_per_object,\n"
"        args->threads_per_mesh\n"
"    );\n"
"}\n";

#endif
