#ifndef LUMINARY_RHI_COMMON_H
#define LUMINARY_RHI_COMMON_H

#include <stdint.h>

#define LUMINARY_OPAQUE_TYPE(name) typedef struct name##_opaque* name

typedef enum LRHIBackend {
    LUMINARY_RHI_BACKEND_VULKAN,
    LUMINARY_RHI_BACKEND_D3D12,
    LUMINARY_RHI_BACKEND_METAL3,
    LUMINARY_RHI_BACKEND_METAL4,
    LUMINARY_RHI_BACKEND_SWITCH,
    LUMINARY_RHI_BACKEND_PLAYSTATION
} LRHIBackend;

typedef enum LRHIErrorSeverity {
    LUMINARY_RHI_ERROR_SEVERITY_SUCCESS,
    LUMINARY_RHI_ERROR_SEVERITY_WARNING,
    LUMINARY_RHI_ERROR_SEVERITY_ERROR
} LRHIErrorSeverity;

typedef enum LRHIShaderBytecode {
    LUMINARY_RHI_SHADER_BYTECODE_SPIRV, // HLSL SPIRV -> Vulkan
    LUMINARY_RHI_SHADER_BYTECODE_DXIL, // HLSL DXC -> D3D12
    LUMINARY_RHI_SHADER_BYTECODE_METAL_FROM_MSL, // MSL -> Metal
    LUMINARY_RHI_SHADER_BYTECODE_METAL_FROM_MSC // HLSL DXC -> Metal Shader Converter -> Metal
} LRHIShaderBytecode;

typedef enum LRHIShaderStage {
    LUMINARY_RHI_SHADER_STAGE_VERTEX,
    LUMINARY_RHI_SHADER_STAGE_FRAGMENT,
    LUMINARY_RHI_SHADER_STAGE_COMPUTE,
    LUMINARY_RHI_SHADER_STAGE_MESH,
    LUMINARY_RHI_SHADER_STAGE_TASK
} LRHIShaderStage;

typedef struct LRHIError {
    char message[256];
    LRHIErrorSeverity severity;
} LRHIError;

#endif
